### ISSUE TITLE
Random Page-Fault/Triple-Fault

### ISSUE THREAD

**Issue by narmour** [ix-project/dune#10]
Hi,

 Ive noticed seemingly random Page-Fault or Triple fault crashes depending on the Linux kernel version I am on simply entering into dune mode then returning, nothing else. Attached is the dmesg snippet containing crash and some quick pseudo code of what im doing to cause this issue.

Linux 3.16 Page-Fault
Linux 4.10 Triple-Fault

**hello**
```
int main(){
    while(1){
        pid = fork()
        if(pid==0){
            exec("TEST");
           }
         else{
             waitpid(pid);
         }
}
```

**TEST**
``` 
int main(){
    dune_init_and_enter();
    return 0;
}
```

When running the **hello** executable, the crashes happen at seemingly random times. They are more frequent on kver 3.16. This can run for 20 minutes or it can crash right away or anywhere in between. Seems to be random. Any ideas as to what the cause would be?

[page_fault.txt](https://github.com/ix-project/dune/files/1729851/page_fault.txt)

**Comment by prekageo** [comment]
Please provide the test binary.

**Comment by narmour** [comment]
Attached is a zip containing the **hello** and **simple** executables.  Please `sudo ./hello` from within the directory to perform the test. 

Note these tests were ran using the unmodified stock (https://github.com/project-dune/dune.git) libdune/kern. I have tried using the IX-kern as well. However the IX-libdune has not been able to enter dune_mode properly on my systems so I have not tried that yet.

On Linux 3.16, this ran for about 20 seconds, on Linux 4.10 with https://github.com/ix-project/dune/commit/1ca0d304893acdcc0353bef8c81d15ae1d0e3cfe patch applied to the default kern this ran for a few minutes.


[crash.zip](https://github.com/ix-project/dune/files/1732401/crash.zip)

**Comment by prekageo** [comment]
I can't reproduce the problem on Linux 4.11. I've let `hello` run for 25 minutes. Moreover, the binaries you provided don't match with the crash that you have attached. Specifically, I can't find the `RIP 0x401cd7` in them.

**Comment by narmour** [comment]
Sorry for the mixup... Just now on a machine running Ubuntu 16.04, Kernel version 4.11.0, using the unmodified dune kern/libdune (aside from the one minor patch to get the kern to compile on 4.11) I was able to get a crash dump after 7 minutes of `sudo ./hello` 



The RIP of the crash is at 0x401ba7   `objdump -d simple | grep 401ba7`. Re-attaching the binaries and crash_log.txt

``` 
0000000000401ba7 <__dune_ret_fail>:
  401ba7:       4c 8b 7c 24 68          mov    0x68(%rsp),%r15
```

[crash.zip](https://github.com/ix-project/dune/files/1748822/crash.zip)

**Comment by narmour** [comment]
Were you using the IX kern/libdune or the default ones? Also which version of 4.11.x have you been running on? I noticed with 4.11.13 dune has new compiler errors I have not seen before.

**Comment by prekageo** [comment]
I am running Ubuntu with kernel 4.11.0-13-generic. I am using dune at commit caef2154a073fa3a44ee92b7aadbc95d15b93d2b. Have you modified the dune kernel module? Who prints this line: `vmx: FS.base 0x0000000000917880 GS.base 0x0000000000000000`? I suspect that the guest page tables are not correct. Are you running with ASLR enabled? Check `/proc/sys/kernel/randomize_va_space`. If yes, disable it and try again.

**Comment by narmour** [comment]
I was running with the kern from **git clone https://github.com/project-dune/dune.git**. I did not touch the kernel module files other than **#define VMX_EPT_EXTENT_INDIVIDUAL_ADDR 0**

Yes, I too suspect that something sour is happening in libdune with regards to the **pgroot** initialization before we vmentry into the guest, however I have not been able to find anything as of yet..

I have always had KASLR turned off as that causes dune to not be able to find the sys_call_table. 
**edit: ahh KASLR !=ASLR,  am turning this off and will try again**

I will try using the same kernel module version as you

**Comment by narmour** [comment]
`vmx: FS.base 0x0000000000917880 GS.base 0x0000000000000000`  is printed out by  the **vmx_dump_cpu** function in **vmx.c**

 ```
printk(KERN_INFO "vmx: FS.base 0x%016lx GS.base 0x%016lx\n",
            vmcs_readl(GUEST_FS_BASE), vmcs_readl(GUEST_GS_BASE));
```

**Comment by narmour** [comment]
Alright, turning off ASLR via `/proc/sys/kernel/randomize_va_space` seems to be the fix. Would still be interesting to know why that is causing issues, but it is stable now... Thank you for taking the time to look at this.
