### ISSUE TITLE
about perf tools problem

### ISSUE THREAD

**Issue by duguhaotian** [ix-project/dune#3]
"perf top" can't show anything.
"perf kvm top" command also no anything.
how about ix support to perf tools ??

**Comment by duguhaotian** [comment]
anyone know something about perf for this project????

**Comment by duguhaotian** [comment]
modify kernel code

 `
unsigned long perf_misc_flags(struct pt_regs *regs)
{
        int misc = 0;

```
    if (perf_guest_cbs && perf_guest_cbs->is_in_guest()) {
            if (perf_guest_cbs->is_user_mode() > 0)
                    misc |= PERF_RECORD_MISC_GUEST_USER;
            else if (perf_guest_cbs->is_user_mode() == -1)
                    misc |= PERF_RECORD_MISC_USER;
            else
                    misc |= PERF_RECORD_MISC_GUEST_KERNEL;
    } else {
            if (user_mode(regs))
                    misc |= PERF_RECORD_MISC_USER;
            else
                    misc |= PERF_RECORD_MISC_KERNEL;
    }

    if (regs->flags & PERF_EFLAGS_EXACT)
            misc |= PERF_RECORD_MISC_EXACT_IP;

    return misc;
```

}
`
and modify dune_guest_cbs

`
static int dune_is_user_mode(void)
{
//      printk(KERN_ERR "this dune_is_user_mode\n");
        return -1;
}
`
and now i can get my method cpu cycles

**Comment by prekageo** [comment]
Sorry for the delayed response.

Can you tell us which Linux kernel version you are using? We have successfully used perf top on Linux 4.4 by doing the following (assuming that you are running IX):

```
# echo '70000000 t _text' > ~/syms
# perf kvm --guestkallsyms ~/syms --guestvmlinux ~/ix top
```

The `~/syms` file is necessary for perf to resolve symbols from the `~/ix` binary.

**Comment by duguhaotian** [comment]
my linux kernel version is 3.1
i will try you advise.
thk very much.
