### ISSUE TITLE
System reboots on dune_enter (in hello test app)

### ISSUE THREAD

**Issue by llvilanova** [ix-project/dune#7]
I've just tried running the `hello` test application inside QEMU (both 2.8 and 2.10 fail at the same point) with KVM and nested virtualization support (host kernel boots with option `kvm-intel.nested=1`).

After the user app calls/requests `dune_enter()`, it ends up in function `vmx_run_vcpu()`; there, as soon as the `vmlaunch` instruction is executed, the machine reboots (I'm not exactly sure at which point the reboot happens and why, but I can't properly debug the guest past that point).

Here's the failing snippet of assembly (around 0xffffffffa0192653):

<pre>
0xffffffffa019264d <vmx_run_vcpu+205>   mov    0x70(%rcx),%rcx
0xffffffffa0192651 <vmx_run_vcpu+209>   jne    0xffffffffa0192658 <vmx_run_vcpu+216>
0xffffffffa0192653 <vmx_run_vcpu+211>   vmlaunch
0xffffffffa0192656 <vmx_run_vcpu+214>   jmp    0xffffffffa019265b <vmx_run_vcpu+219>
0xffffffffa0192658 <vmx_run_vcpu+216>   vmresume
0xffffffffa019265b <vmx_run_vcpu+219>   mov    %rcx,0x8(%rsp)
</pre>

Some VMCS values before calling `vmx_run_vcpu()` (the RIPs are supposed to be set by dune only once during initialization):
* HOST_RIP: 0xffffffffa019265b
* GUEST_RIP: 0x402054

If I step on the `vmlaunch` instruction from QEMU (i.e., attaching gdb to debug the guest system), the next RIP is 0xca5d, obviously wrong (it's neither the host or guest RIPs on the VMCS), and I get this on the host's dmesg (the MSR is PEBS enable, which should not be a problem):

<pre>
[506486.162702] kvm [9162]: vcpu0, guest rIP: 0x402054 unhandled wrmsr: 0x3f1 data 0x0
[506486.162709] kvm [9162]: vcpu0, guest rIP: 0xffffffffa019265b unhandled wrmsr: 0x3f1 data 0x0
</pre>

Also, breakpoints inserted to the host/guest VMCS RIPs are never triggered after stepping through `vmlaunch`.

Any ideas about what to look for or how to fix this?

**Comment by llvilanova** [comment]
And here's a trace of `kvm_exit` on the host kernel:

<pre>
qemu-system-x86-29132 [002] .... 516160.273392: kvm_exit: reason PREEMPTION_TIMER rip 0xffffffffa019f693 info 0 0
qemu-system-x86-29132 [002] .... 516160.273402: kvm_exit: reason MSR_WRITE rip 0xffffffff81047dd4 info 0 0
qemu-system-x86-29132 [002] .... 516160.273405: kvm_exit: reason VMLAUNCH rip 0xffffffffa019f693 info 0 0
qemu-system-x86-29132 [002] .... 516160.280399: kvm_exit: reason PREEMPTION_TIMER rip 0xfff0 info 0 0
qemu-system-x86-29132 [002] .... 516160.280401: kvm_exit: reason EPT_VIOLATION rip 0xfff0 info 184 0
qemu-system-x86-29132 [002] .... 516160.280412: kvm_exit: reason EPT_VIOLATION rip 0xe05b info 184 0
qemu-system-x86-29132 [002] .... 516160.280418: kvm_exit: reason EPT_VIOLATION rip 0xe05b info 181 0
qemu-system-x86-29132 [002] .... 516160.280421: kvm_exit: reason EPT_VIOLATION rip 0xcda5 info 182 0
qemu-system-x86-29132 [002] .... 516160.280423: kvm_exit: reason IO_INSTRUCTION rip 0xcdaf info 700040 0
qemu-system-x86-29132 [002] .... 516160.280429: kvm_exit: reason IO_INSTRUCTION rip 0xcdb1 info 710048 0
</pre>

**Comment by prekageo** [comment]
Running Dune inside KVM is not supported. I was able to do it when I commented out the call to setup_perf_msrs inside vmx_launch of kern/vmx.c (https://github.com/ix-project/dune/blob/master/kern/vmx.c#L1753). I am not sure if this trick still works, though.

**Comment by llvilanova** [comment]
Aha! I should have thought about it, thanks :)

The problem is that Intel's PEBS writes into some physical addresses that I suspect are not mapped (or incorrectly so) on the nested guest (i.e., the dune VM). I just haven't figured out yet why this does not happen in dune on a host.

I guess that the proper solution would be to make sure PEBS' buffers are available in dune's VM, but I'm too lazy for that (I'm not even sure it makes sense to keep it enabled). So what I did is skipping `MSR_IA32_PEBS_ENABLE` in `setup_perf_msrs` (since its passed by Linux's `perf_guest_get_msrs`).

I suppose the ideal would be to disable it only on a nested guest; but again, I'm not even sure it makes sense to keep it enabled at all (maybe it works in non-nested guests by pure chance only, just because nobody uses it together with dune).

PS: I can send a pull request with the fix above, including nested guest detection if deemed necessary.

**Comment by prekageo** [comment]
Do you have some reasonable use case for running Dune inside a virtual machine? If yes, then we could accept such a pull request. Otherwise, I think it's safer to not support such a scenario.

**Comment by llvilanova** [comment]
Proper debugging with gdb attached to QEMU running IX.
