### ISSUE TITLE
Triple fault on dune enter (in hello test app)

### ISSUE THREAD

**Issue by llvilanova** [ix-project/dune#8]
After fixing #7, I've run into a new problem (triple fault error) when running the `test` app inside QEMU (same configuration as #7).

At the bottom there's a combined output of the test app, and a few extra kernel messages I added to dune (dune's VM exit reasons on the guest OS running inside QEMU, and addresses of EPT faults).

Any idea where this might be coming from?

<pre>
hello: not running dune yet
hello: main: 0x400d80
dune_init: dune_layout::phys_limit 0x10000000000
dune_init: dune_layout::base_map 0x7f6180000000
dune_init: dune_layout::base_stack 0x7ffe40000000
--- Process Map Dump ---
0x0000000000400000-0x0000000000409000 R-XP 00000000 /mnt/build/ix/deps/dune/test/hello
0x0000000000608000-0x0000000000609000 R-XP 00008000 /mnt/build/ix/deps/dune/test/hello
0x0000000000609000-0x000000000060c000 RWXP 00009000 /mnt/build/ix/deps/dune/test/hello
0x000000000060c000-0x000000000060e000 RWXP 00000000 
0x000000000072a000-0x000000000074b000 RWXP 00000000 [heap]
0x0000000200000000-0x0000000208a00000 RWXP 00000000 
0x00007f710b7d3000-0x00007f710c7d4000 RWXP 00000000 
0x00007f710c7d4000-0x00007f710c994000 R-XP 00000000 /lib/x86_64-linux-gnu/libc-2.23.so
0x00007f710c994000-0x00007f710cb94000 ---P 001c0000 /lib/x86_64-linux-gnu/libc-2.23.so
0x00007f710cb94000-0x00007f710cb98000 R-XP 001c0000 /lib/x86_64-linux-gnu/libc-2.23.so
0x00007f710cb98000-0x00007f710cb9a000 RWXP 001c4000 /lib/x86_64-linux-gnu/libc-2.23.so
0x00007f710cb9a000-0x00007f710cb9e000 RWXP 00000000 
0x00007f710cb9e000-0x00007f710cbb6000 R-XP 00000000 /lib/x86_64-linux-gnu/libpthread-2.23.so
0x00007f710cbb6000-0x00007f710cdb5000 ---P 00018000 /lib/x86_64-linux-gnu/libpthread-2.23.so
0x00007f710cdb5000-0x00007f710cdb6000 R-XP 00017000 /lib/x86_64-linux-gnu/libpthread-2.23.so
0x00007f710cdb6000-0x00007f710cdb7000 RWXP 00018000 /lib/x86_64-linux-gnu/libpthread-2.23.so
0x00007f710cdb7000-0x00007f710cdbb000 RWXP 00000000 
0x00007f710cdbb000-0x00007f710cde1000 R-XP 00000000 /lib/x86_64-linux-gnu/ld-2.23.so
0x00007f710cfd4000-0x00007f710cfd7000 RWXP 00000000 
0x00007f710cfde000-0x00007f710cfe0000 RWXP 00000000 
0x00007f710cfe0000-0x00007f710cfe1000 R-XP 00025000 /lib/x86_64-linux-gnu/ld-2.23.so
0x00007f710cfe1000-0x00007f710cfe2000 RWXP 00026000 /lib/x86_64-linux-gnu/ld-2.23.so
0x00007f710cfe2000-0x00007f710cfe3000 RWXP 00000000 
0x00007ffe49ac4000-0x00007ffe49ae5000 RWXP 00000000 [stack]
0x00007ffe49b7d000-0x00007ffe49b7f000 R--P 00000000 [vvar]
0x00007ffe49b7f000-0x00007ffe49b81000 R-XP 00000000 [vdso]
0xffffffffff600000-0xffffffffff601000 R-XP 00000000 [vsyscall]
[  619.240362] R ffffffff819060d0
[  619.240586] vmx: created VCPU (VPID 1)
[  619.241607] vmx_run_vcpu: VMCS::GUEST_RIP: 0x402304
[  619.241607] vmx_run_vcpu: VMCS::GUEST_RSP: 0x7ffe49ae3370
[  619.241608] vmx_run_vcpu: VMCS::HOST_RIP: 0xffffffffa0086692
[  619.241609] vmx_run_vcpu: VMCS::HOST_RSP: 0x0
[  620.245268] vmx_launch: VM_EXIT_REASON: 48 - EPT violation
[  620.246041] vmx_launch: EXIT_QUALIFICATION: 0x83
[  621.269271] ept: GPA: 0x72b000, GVA: 0x402304, HVA: 0x72b000, flags: 83
[  621.269295] vmx_run_vcpu: VMCS::GUEST_RIP: 0x402304
[  621.269295] vmx_run_vcpu: VMCS::GUEST_RSP: 0x7ffe49ae3370
[  621.269297] vmx_run_vcpu: VMCS::HOST_RIP: 0xffffffffa0086692
[  621.269297] vmx_run_vcpu: VMCS::HOST_RSP: 0xffffc90001dc7d18
[  622.293335] vmx_launch: VM_EXIT_REASON: 48 - EPT violation
[  622.294116] vmx_launch: EXIT_QUALIFICATION: 0x83
[  623.317270] ept: GPA: 0x2001ff000, GVA: 0x402304, HVA: 0x2001ff000, flags: 83
[  623.317295] vmx_run_vcpu: VMCS::GUEST_RIP: 0x402304
[  623.317295] vmx_run_vcpu: VMCS::GUEST_RSP: 0x7ffe49ae3370
[  623.317297] vmx_run_vcpu: VMCS::HOST_RIP: 0xffffffffa0086692
[  623.317297] vmx_run_vcpu: VMCS::HOST_RSP: 0xffffc90001dc7d18
[  624.341290] vmx_launch: VM_EXIT_REASON: 48 - EPT violation
[  624.342072] vmx_launch: EXIT_QUALIFICATION: 0x83
[  625.365246] ept: GPA: 0x2001fe010, GVA: 0x402304, HVA: 0x2001fe010, flags: 83
[  625.365261] vmx_run_vcpu: VMCS::GUEST_RIP: 0x402304
[  625.365261] vmx_run_vcpu: VMCS::GUEST_RSP: 0x7ffe49ae3370
[  625.365263] vmx_run_vcpu: VMCS::HOST_RIP: 0xffffffffa0086692
[  625.365263] vmx_run_vcpu: VMCS::HOST_RSP: 0xffffc90001dc7d18
[  626.389316] vmx_launch: VM_EXIT_REASON: 48 - EPT violation
[  626.390098] vmx_launch: EXIT_QUALIFICATION: 0x83
[  627.413205] ept: GPA: 0x2001fb010, GVA: 0x402304, HVA: 0x2001fb010, flags: 83
[  627.413218] vmx_run_vcpu: VMCS::GUEST_RIP: 0x402304
[  627.413219] vmx_run_vcpu: VMCS::GUEST_RSP: 0x7ffe49ae3370
[  627.413220] vmx_run_vcpu: VMCS::HOST_RIP: 0xffffffffa0086692
[  627.413221] vmx_run_vcpu: VMCS::HOST_RSP: 0xffffc90001dc7d18
[  628.437314] vmx_launch: VM_EXIT_REASON: 48 - EPT violation
[  628.438106] vmx_launch: EXIT_QUALIFICATION: 0x184
[  629.461263] ept: GPA: 0x402304, GVA: 0x402304, HVA: 0x402304, flags: 184
[  629.461288] vmx_run_vcpu: VMCS::GUEST_RIP: 0x402304
[  629.461288] vmx_run_vcpu: VMCS::GUEST_RSP: 0x7ffe49ae3370
[  629.461289] vmx_run_vcpu: VMCS::HOST_RIP: 0xffffffffa0086692
[  629.461290] vmx_run_vcpu: VMCS::HOST_RSP: 0xffffc90001dc7d18
[  630.485323] vmx_launch: VM_EXIT_REASON: 48 - EPT violation
[  630.486109] vmx_launch: EXIT_QUALIFICATION: 0x83
[  631.509259] ept: GPA: 0x2087bafc8, GVA: 0x7ffe49ae33d8, HVA: 0x2087bafc8, flags: 83
[  631.509283] vmx_run_vcpu: VMCS::GUEST_RIP: 0x402307
[  631.509283] vmx_run_vcpu: VMCS::GUEST_RSP: 0x7ffe49ae3370
[  631.509285] vmx_run_vcpu: VMCS::HOST_RIP: 0xffffffffa0086692
[  631.509285] vmx_run_vcpu: VMCS::HOST_RSP: 0xffffc90001dc7d18
[  632.533323] vmx_launch: VM_EXIT_REASON: 48 - EPT violation
[  632.534118] vmx_launch: EXIT_QUALIFICATION: 0x83
[  633.557257] ept: GPA: 0x2087b9268, GVA: 0x7ffe49ae33d8, HVA: 0x2087b9268, flags: 83
[  633.557273] vmx_run_vcpu: VMCS::GUEST_RIP: 0x402307
[  633.557273] vmx_run_vcpu: VMCS::GUEST_RSP: 0x7ffe49ae3370
[  633.557275] vmx_run_vcpu: VMCS::HOST_RIP: 0xffffffffa0086692
[  633.557275] vmx_run_vcpu: VMCS::HOST_RSP: 0xffffc90001dc7d18
[  634.581306] vmx_launch: VM_EXIT_REASON: 48 - EPT violation
[  634.582095] vmx_launch: EXIT_QUALIFICATION: 0x83
[  635.605259] ept: GPA: 0x20876b718, GVA: 0x7ffe49ae33d8, HVA: 0x20876b718, flags: 83
[  635.605274] vmx_run_vcpu: VMCS::GUEST_RIP: 0x402307
[  635.605275] vmx_run_vcpu: VMCS::GUEST_RSP: 0x7ffe49ae3370
[  635.605276] vmx_run_vcpu: VMCS::HOST_RIP: 0xffffffffa0086692
[  635.605277] vmx_run_vcpu: VMCS::HOST_RSP: 0xffffc90001dc7d18
[  636.629324] vmx_launch: VM_EXIT_REASON:  2 - triple fault
[  636.630136] vmx_launch: EXIT_QUALIFICATION: 0x0
[  637.653253] unhandled exit: reason 2, exit qualification 0
[  637.653254] vmx: --- Begin VCPU Dump ---
[  637.653254] vmx: CPU 0 VPID 1
[  637.653255] vmx: RIP 0x0000000000402307 RFLAGS 0x00010046
[  637.653256] vmx: RAX 0x0000000000000000 RCX 0x000000000072a410
[  637.653256] vmx: RDX 0x0000000000000000 RBX 0x000000000072a410
[  637.653256] vmx: RSP 0x00007ffe49ae3370 RBP 0x0000000000000000
[  637.653257] vmx: RSI 0x0000000000000000 RDI 0x0000000000000000
[  637.653257] vmx: R8  0x0000000000000000 R9  0x0000000000000000
[  637.653257] vmx: R10 0x0000000000000000 R11 0x0000000000000000
[  637.653258] vmx: R12 0x00007f710cb99540 R13 0x00000000ffffffff
[  637.653258] vmx: R14 0x0000000000000000 R15 0x0000000000000000
[  637.653258] vmx: Dumping Stack Contents...
[  637.653259] vmx: RSP+0  0x0000000000000003
[  637.653260] vmx: RSP+8  0x000000000072a420
[  637.653260] vmx: RSP+16 0x000000000072b000
[  637.653261] vmx: RSP+24 0x00007f710cb98b20
[  637.653261] vmx: RSP+32 0x00007f710cb99158
[  637.653261] vmx: RSP+40 0x0000000000000001
[  637.653261] vmx: RSP+48 0x00007f710cfd5700
[  637.653262] vmx: RSP+56 0x0000000000000246
[  637.653262] vmx: RSP+64 0x00007f710cfdb000
[  637.653262] vmx: RSP+72 0x00007f710cfdb000
[  637.653263] vmx: RSP+80 0x0000000000400e10
[  637.653263] vmx: RSP+88 0x00007ffe49ae3510
[  637.653263] vmx: --- End VCPU Dump ---
[  637.653264] vmx: stopping VCPU (VPID 1)
dune: exit due to unhandled VM exit
[  637.658240] vmx: destroying VCPU (VPID 1)
</pre>

**Comment by prekageo** [comment]
Works for me with Ubuntu Linux 4.11.0-13-generic and QEMU emulator version 2.5.0. Try to pass `-cpu host` as a qemu parameter. Give me the `cat /proc/cpuinfo` from inside the VM.

**Comment by llvilanova** [comment]
I'm on a Debian host (mostly latest stable with some testing pkgs in it) with Linux 4.9.0-4-amd64 and QEMU 2.10.0+dfsg-2 with `-cpu host`. The guest is Ubuntu 16.04.3, with a home-compiled Linux 4.10.1+ (to get proper debug info when attaching the host gdb to the guest's kernel). Here's the guest CPU info:

<pre>
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 60
model name	: Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
stepping	: 3
microcode	: 0x1
cpu MHz		: 3292.374
cache size	: 16384 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt arat
bugs		:
bogomips	: 6584.74
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:
</pre>

**Comment by prekageo** [comment]
The only thing that I can see that you fail here:
```
0000000000402733 <__dune_ret>:
  402733:       xor    rax,rax

0000000000402736 <__dune_ret_fail>:
  402736:       mov    r15,QWORD PTR [rsp+0x68] <---
  40273b:       mov    r14,QWORD PTR [rsp+0x60]
```

Which means that you don't have access to the stack within Dune. The last 3 EPT violations are because Dune has to create the page tables for that access. But then I don't see the EPT violation for the memory location itself. Also, triple fault means that something bad happens when you try to deal with exceptions inside Dune. So, most probably after the 3 EPT violations, a #PF is raised, which somehow results in a #DF, which somehow results in a triple fault.

**Comment by llvilanova** [comment]
Is your Linux 4.11.0-13-generic on the host or the guest? (or both) I tried installing that kernel package on the guest, and I still get the triple fault.

Also, this is my QEMU cmdline:

<pre>
sudo qemu-system-x86_64 \
	-s \
	-snapshot \
	-enable-kvm \
	-cpu host \
	-smp 1 \
	-m 8G \
	-serial stdio \
	-rtc base=localtime,clock=vm,driftfix=none \
	-netdev user,id=wire,net=192.168.76.0/24,dhcpstart=192.168.76.9,hostfwd=tcp::2222-:22 \
	-device e1000,netdev=wire \
	-netdev tap,id=dpdk,queues=1 \
	-device virtio-net-pci,netdev=dpdk,mq=on,vectors=$((2 + (1 * 2))) \
	-hda deps/system.img \
	-virtfs local,path=/home/lluis/Projects/dos.experiments,mount_tag=host0,security_model=passthrough,id=host0
</pre>

**Comment by prekageo** [comment]
I use the following Bash script:
```
#!/bin/bash

set -e

make -sj64

mkdir -p /tmp/initrd/lib/x86_64-linux-gnu /tmp/initrd/bin /tmp/initrd/lib64 /tmp/initrd/usr/lib/x86_64-linux-gnu /tmp/initrd/dev /tmp/initrd/proc /tmp/initrd/sys

cp -aL {,/tmp/initrd}/lib64/ld-linux-x86-64.so.2
cp -aL {,/tmp/initrd}/lib/x86_64-linux-gnu/libc.so.6
cp -aL {,/tmp/initrd}/lib/x86_64-linux-gnu/libpthread.so.0
cp -aL {,/tmp/initrd}/lib/x86_64-linux-gnu/librt.so.1
cp -aL {,/tmp/initrd}/lib/x86_64-linux-gnu/libm.so.6
cp -aL {,/tmp/initrd}/usr/lib/x86_64-linux-gnu/libnuma.so.1
cp -aL {,/tmp/initrd}/lib/x86_64-linux-gnu/libdl.so.2
cp -aL {,/tmp/initrd}/usr/lib/x86_64-linux-gnu/libconfig.so.9
cp ix/deps/dune/kern/dune.ko /tmp/initrd
cp ix/dp/ix /tmp/initrd
cp ix/ix.conf /tmp/initrd

cp -a {,/tmp/initrd}/bin/busybox
sudo chroot /tmp/initrd /bin/busybox --install -s /bin

cat > /tmp/initrd/init <<"EOF"
#!/bin/sh

mount -t sysfs sysfs /sys
mount -t proc proc /proc
mount -t devtmpfs dev /dev
mkdir /dev/shm
mount -t tmpfs tmpfs /dev/shm
echo 0 > /proc/sys/kernel/randomize_va_space
dmesg -n 8
echo 4096 > /sys/devices/system/node/node0/hugepages/hugepages-2048kB/nr_hugepages
# cat /proc/cpuinfo
insmod dune.ko
./ix -c ix.conf

EOF
chmod +x /tmp/initrd/init
( cd /tmp/initrd && find . | cpio -o -H newc 2> /dev/null | gzip > /tmp/initrd.gz )

sudo qemu-system-x86_64 -nographic -kernel /boot/vmlinuz-`uname -r` -initrd /tmp/initrd.gz -append 'console=ttyS0 quiet nmi_watchdog=1' -cpu host,-x2apic -enable-kvm

```

**Comment by llvilanova** [comment]
Just changing to another machine did the trick (Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz). I haven't looked at why exactly, though, but I suppose you can close this issue.

PS: Thanks for the initrd script!
